In [5]:
import numpy as np
from sklearn.metrics import mean_absolute_error
actual_value = [2, 3, 4, 8, 4]
predicted_value = [4, 5, 9, 1, 7]
mae = mean_absolute_error(actual_value, predicted_value)
print(f"Mean Absoult_error: {mae}")

Mean Absoult_error: 3.8


In [6]:
from sklearn.metrics import r2_score
actual_values = [10, 20, 30, 40, 50]
predicted_values = [12, 18, 28, 38, 52]
r2 = r2_score(actual_values, predicted_values)
print(f"R-squared (R2) Score: {r2}")

R-squared (R2) Score: 0.98


In [7]:
from sklearn.metrics import mean_squared_error
actual_value = [2, 4, 7, 8]
predicted_value = [4, 1, 6, 9]
sqrt = mean_squared_error(actual_value, predicted_value)
rmse = sqrt
print(f"Root mean squared error:{rmse}")

Root mean squared error:3.75


# hold out method

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris 
data = load_iris()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

# LeaveOneOut

In [9]:
from sklearn.model_selection import LeaveOneOut
from sklearn.linear_model import LinearRegression
loo = LeaveOneOut()
total_mse = 0
for train_index, test_index in loo.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    total_mse += mse

average_mse = total_mse / len(X)
print("Average Mean Squared Error (LOOCV):", average_mse)

Average Mean Squared Error (LOOCV): 0.04954185325184582


# kFold

In [10]:
from sklearn.model_selection import kFold
k = 5
kf = kFolde(n_splits=k)
total_mse = 0
for train_index, test_index in k-fold.split(x):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[text_index]
    model = linearRegresson()
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    mse = mean_squared_error(y_test, y_pred)
    total_mse += mse
average_mse = total_mse / k-fold(x)
print("average_mse")

ImportError: cannot import name 'kFold' from 'sklearn.model_selection' (C:\Users\Anusha V\anaconda3\lib\site-packages\sklearn\model_selection\__init__.py)

In [11]:
import pandas as pd
df = pd.read_csv (r"C:\Users\Anusha V\Downloads\archive (8)\APY.csv")
print(df)

                             State District       Crop  Crop_Year  \
0       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
1       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
2       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
3       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
4       Andaman and Nicobar Island  NICOBARS  Arecanut       2009   
...                            ...       ...       ...        ...   
345331                 West Bengal   PURULIA     Wheat       2015   
345332                 West Bengal   PURULIA     Wheat       2016   
345333                 West Bengal   PURULIA     Wheat       2017   
345334                 West Bengal   PURULIA     Wheat       2018   
345335                 West Bengal   PURULIA     Wheat       2019   

             Season   Area   Production  Yield  
0       Kharif       2439.6      3415.0   1.40  
1       Rabi         1626.4      2277.0   1.40  
2       Autumn       414

In [12]:
df.head(100)

State                 District       Crop  Crop_Year  \
0   Andaman and Nicobar Island                  NICOBARS  Arecanut       2007   
1   Andaman and Nicobar Island                  NICOBARS  Arecanut       2007   
2   Andaman and Nicobar Island                  NICOBARS  Arecanut       2008   
3   Andaman and Nicobar Island                  NICOBARS  Arecanut       2008   
4   Andaman and Nicobar Island                  NICOBARS  Arecanut       2009   
..                         ...                       ...       ...        ...   
95  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2015   
96  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2016   
97  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2017   
98  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2018   
99  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2019   

         Season    Area   Production  Yield  
0   Kharif       2439.60      3415.0   1.40  
1   Rabi         1626.40      2277.0   1.40  
2   Autumn       4147.00      3060.0   0.74  
3   Summer       4147.00      2660.0   0.64  
4   Autumn       4153.00      3120.0   0.75  
..          ...      ...         ...    ...  
95  Whole Year   1178.00     11180.0   9.49  
96  Whole Year   1012.00      5226.0   5.16  
97  Whole Year    584.85      4944.0   8.45  
98  Whole Year    650.54      6999.0  10.76  
99  Whole Year    665.12      5904.0   8.88  

[100 rows x 8 columns]

In [13]:
df.head(100)

State                 District       Crop  Crop_Year  \
0   Andaman and Nicobar Island                  NICOBARS  Arecanut       2007   
1   Andaman and Nicobar Island                  NICOBARS  Arecanut       2007   
2   Andaman and Nicobar Island                  NICOBARS  Arecanut       2008   
3   Andaman and Nicobar Island                  NICOBARS  Arecanut       2008   
4   Andaman and Nicobar Island                  NICOBARS  Arecanut       2009   
..                         ...                       ...       ...        ...   
95  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2015   
96  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2016   
97  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2017   
98  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2018   
99  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN    Banana       2019   

         Season    Area   Production  Yield  
0   Kharif       2439.60      3415.0   1.40  
1   Rabi         1626.40      2277.0   1.40  
2   Autumn       4147.00      3060.0   0.74  
3   Summer       4147.00      2660.0   0.64  
4   Autumn       4153.00      3120.0   0.75  
..          ...      ...         ...    ...  
95  Whole Year   1178.00     11180.0   9.49  
96  Whole Year   1012.00      5226.0   5.16  
97  Whole Year    584.85      4944.0   8.45  
98  Whole Year    650.54      6999.0  10.76  
99  Whole Year    665.12      5904.0   8.88  

[100 rows x 8 columns]

In [14]:
df.describe()

Crop_Year         Area     Production          Yield
count  345336.000000  3.453360e+05  3.403880e+05  345336.000000
mean     2008.887512  1.167147e+04  9.584726e+05      79.423135
std         6.564361  4.584079e+04  2.153068e+07     916.678396
min      1997.000000  4.000000e-03  0.000000e+00       0.000000
25%      2003.000000  7.400000e+01  8.700000e+01       0.550000
50%      2009.000000  5.320000e+02  7.170000e+02       1.000000
75%      2015.000000  4.112000e+03  7.182000e+03       2.470000
max      2020.000000  8.580100e+06  1.597800e+09   43958.330000

In [15]:
sum = df['Yield'].sum()
sum

27427667.91

In [16]:
sum = df['Yield'].mean()
sum

79.42313546806362

In [17]:
sum = df['Yield'].median()
sum

1.0

In [18]:
sum = df['Yield'].var()
sum

840299.2822745175

In [19]:
sum = df['Yield'].std()
sum

916.6783963171148

In [20]:
df.isnull

<bound method DataFrame.isnull of                              State District       Crop  Crop_Year  \
0       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
1       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
2       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
3       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
4       Andaman and Nicobar Island  NICOBARS  Arecanut       2009   
...                            ...       ...       ...        ...   
345331                 West Bengal   PURULIA     Wheat       2015   
345332                 West Bengal   PURULIA     Wheat       2016   
345333                 West Bengal   PURULIA     Wheat       2017   
345334                 West Bengal   PURULIA     Wheat       2018   
345335                 West Bengal   PURULIA     Wheat       2019   

             Season   Area   Production  Yield  
0       Kharif       2439.6      3415.0   1.40  
1       Rabi         1626.4      2277.0

In [21]:
df.isnull().sum().sum()

4957

In [22]:
d_f = df.fillna(100)
d_f

State District       Crop  Crop_Year  \
0       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
1       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
2       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
3       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
4       Andaman and Nicobar Island  NICOBARS  Arecanut       2009   
...                            ...       ...       ...        ...   
345331                 West Bengal   PURULIA     Wheat       2015   
345332                 West Bengal   PURULIA     Wheat       2016   
345333                 West Bengal   PURULIA     Wheat       2017   
345334                 West Bengal   PURULIA     Wheat       2018   
345335                 West Bengal   PURULIA     Wheat       2019   

             Season   Area   Production  Yield  
0       Kharif       2439.6      3415.0   1.40  
1       Rabi         1626.4      2277.0   1.40  
2       Autumn       4147.0      3060.0   0.74  
3       Summer       4147.0      2660.0   0.64  
4       Autumn       4153.0      3120.0   0.75  
...             ...     ...         ...    ...  
345331  Rabi          855.0      1241.0   1.45  
345332  Rabi         1366.0      2415.0   1.77  
345333  Rabi         1052.0      2145.0   2.04  
345334  Rabi          833.0      2114.0   2.54  
345335  Rabi          516.0       931.0   1.80  

[345336 rows x 8 columns]

In [23]:
d_f = df.dropna(0)
d_f

C:\Users\Anusha V\AppData\Local\Temp\ipykernel_18744\1675708418.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only.
  d_f = df.dropna(0)


State District       Crop  Crop_Year  \
0       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
1       Andaman and Nicobar Island  NICOBARS  Arecanut       2007   
2       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
3       Andaman and Nicobar Island  NICOBARS  Arecanut       2008   
4       Andaman and Nicobar Island  NICOBARS  Arecanut       2009   
...                            ...       ...       ...        ...   
345331                 West Bengal   PURULIA     Wheat       2015   
345332                 West Bengal   PURULIA     Wheat       2016   
345333                 West Bengal   PURULIA     Wheat       2017   
345334                 West Bengal   PURULIA     Wheat       2018   
345335                 West Bengal   PURULIA     Wheat       2019   

             Season   Area   Production  Yield  
0       Kharif       2439.6      3415.0   1.40  
1       Rabi         1626.4      2277.0   1.40  
2       Autumn       4147.0      3060.0   0.74  
3       Summer       4147.0      2660.0   0.64  
4       Autumn       4153.0      3120.0   0.75  
...             ...     ...         ...    ...  
345331  Rabi          855.0      1241.0   1.45  
345332  Rabi         1366.0      2415.0   1.77  
345333  Rabi         1052.0      2145.0   2.04  
345334  Rabi          833.0      2114.0   2.54  
345335  Rabi          516.0       931.0   1.80  

[340383 rows x 8 columns]

In [3]:
import pandas as pd
data = {
    'CIE': [50, 60, 70, 80, 90,5,15],
    'SEE': [55, 65, 75, 85, 95,12,4]
}

data = pd.DataFrame(data)


In [8]:
from sklearn.model_selection import train_test_split
X = data[['CIE']].values  # Independent variable
y = data['SEE'].values    # Dependent variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [9]:
X

array([[50],
       [60],
       [70],
       [80],
       [90],
       [ 5],
       [15]], dtype=int64)

In [55]:
y

array([55, 65, 75, 85, 95, 12,  4], dtype=int64)